name: vision_assist_app
description: "A Flutter project to assist visually impaired individuals with object detection, face recognition, text reading, and more."

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number
version: 1.0.0+1

# Flutter SDK environment
environment:
  sdk: ^3.5.2

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2 # Camera integration
  google_ml_kit: ^0.18.0 # Machine Learning Kit for object detection
  google_mlkit_face_detection: ^0.11.0 # Face detection using ML Kit
  http: ^1.2.2 # For API calls
  flutter_tts: ^4.0.2 # Text-to-speech functionality
  speech_to_text: ^7.0.0 # Speech recognition
  image_picker: ^1.1.2 # Image picking from gallery or camera
  path_provider: ^2.0.7 # Path provider for file system paths
  permission_handler: ^11.3.1 # Handling runtime permissions
  flutter_sound: ^9.2.13 # Sound recording and playback
  record: ^4.0.0 # Recording audio
  mime: ^1.0.2 # MIME type handling
  cupertino_icons: ^1.0.8 # iOS-style icons

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1" # For app launcher icons
  flutter_lints: ^4.0.0 # Recommended linting rules

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Specify the location of app assets
  assets:
    - assets/icon/

# Launcher icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
